name: Port Kernel Using Git Clone and Unix Tools

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repo HTTPS URL'
        required: true
        type: string
      source_branch:
        description: 'Source branch'
        required: false
        default: 'main'
        type: string
      target_repo:
        description: 'Target repo HTTPS URL'
        required: true
        type: string
      target_branch:
        description: 'Target branch'
        required: false
        default: 'main'
        type: string

jobs:
  port-and-package:
    runs-on: ubuntu-latest
    env:
      ZIP_OUTPUT: kernel_ported.zip

    steps:
      - name: Clone source repo only
        run: |
          git clone --depth 1 --branch ${{ github.event.inputs.source_branch }} ${{ github.event.inputs.source_repo }} source_repo

      - name: Clone target repo only
        run: |
          git clone --depth 1 --branch ${{ github.event.inputs.target_branch }} ${{ github.event.inputs.target_repo }} target_repo

      - name: Remove target repo contents (keep .git) for clean port
        run: |
          cd target_repo
          shopt -s extglob
          rm -rf !( .git )

      - name: Copy source files into target repo directory, overwriting
        run: |
          cp -a ../source_repo/. ./target_repo/

      - name: Zip the combined source code
        run: |
          cd target_repo
          zip -r ../${ZIP_OUTPUT} .

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: ported-kernel-zip
          path: ${{ env.ZIP_OUTPUT }}
