name: Port Kernel and Upload Zip Artifact

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repo HTTPS URL'
        required: true
        type: string
      source_branch:
        description: 'Source repo branch'
        required: false
        default: 'main'
        type: string
      target_repo:
        description: 'Target repo HTTPS URL'
        required: true
        type: string
      target_branch:
        description: 'Target repo branch'
        required: false
        default: 'main'
        type: string
      merge_method:
        description: 'Merge method (merge or rebase)'
        required: false
        default: 'merge'
        type: string

jobs:
  port-and-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source repo
        run: |
          git clone --branch ${{ github.event.inputs.source_branch }} ${{ github.event.inputs.source_repo }} source_repo

      - name: Clone target repo
        run: |
          git clone --branch ${{ github.event.inputs.target_branch }} ${{ github.event.inputs.target_repo }} target_repo

      - name: Merge or rebase source into target
        run: |
          cd target_repo
          git remote add source ../source_repo
          git fetch source
          if [ "${{ github.event.inputs.merge_method }}" = "rebase" ]; then
            git rebase source/${{ github.event.inputs.source_branch }}
          else
            git merge source/${{ github.event.inputs.source_branch }} --no-ff
          fi

      - name: Zip merged result
        run: |
          cd target_repo
          zip -r ../kernel_ported.zip . 

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ported-kernel-zip
          path: kernel_ported.zip
