name: Port Kernel Commits and Upload Zip Artifact

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repo HTTPS URL (e.g., https://github.com/user/source.git)'
        required: true
        type: string
      source_branch:
        description: 'Source repo branch to port from'
        required: false
        default: 'main'
        type: string
      target_repo:
        description: 'Target repo HTTPS URL (e.g., https://github.com/user/target.git)'
        required: true
        type: string
      target_branch:
        description: 'Target repo branch to port to'
        required: false
        default: 'main'
        type: string
      merge_method:
        description: 'Merge method (merge or rebase)'
        required: false
        default: 'merge'
        type: string

jobs:
  port-and-package:
    runs-on: ubuntu-latest
    env:
      ZIP_OUTPUT: kernel_ported.zip

    steps:
      - name: Checkout source repo (shallow clone for speed)
        run: |
          git clone --depth 1 --branch ${{ github.event.inputs.source_branch }} ${{ github.event.inputs.source_repo }} source_repo

      - name: Checkout target repo (shallow clone for speed)
        run: |
          git clone --depth 1 --branch ${{ github.event.inputs.target_branch }} ${{ github.event.inputs.target_repo }} target_repo

      - name: Configure git user
        run: |
          cd target_repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add source repo remote and fetch commits
        run: |
          cd target_repo
          git remote add source ../source_repo
          git fetch source

      - name: Merge or rebase source branch into target
        run: |
          cd target_repo
          if [ "${{ github.event.inputs.merge_method }}" = "rebase" ]; then
            git rebase source/${{ github.event.inputs.source_branch }}
          else
            git merge source/${{ github.event.inputs.source_branch }} --no-ff --allow-unrelated-histories
          fi

      - name: Clean up git metadata for artifact
        run: |
          cd target_repo
          rm -rf .git

      - name: Zip merged kernel source
        run: |
          cd target_repo
          zip -r ../${ZIP_OUTPUT} .

      - name: Upload ported kernel artifact
        uses: actions/upload-artifact@v3
        with:
          name: ported-kernel-zip
          path: ${{ env.ZIP_OUTPUT }}
